# Generated by Django 5.2.8 on 2025-12-01 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Army',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('formation_name', models.CharField(blank=True, help_text='Nom convivial de la formation enregistrée.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commander',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('gold', models.PositiveIntegerField(default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cost', models.PositiveIntegerField(default=50)),
                ('attack', models.PositiveIntegerField(default=1)),
                ('defense', models.PositiveIntegerField(default=1)),
                ('health', models.PositiveIntegerField(default=5)),
                ('speed', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward', models.PositiveIntegerField(default=0)),
                ('rounds', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('resolved', 'Résolu')], default='pending', max_length=12)),
                ('log', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('attacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacking_battles', to='armies.army')),
                ('defender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defending_battles', to='armies.army')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wins', to='armies.army')),
            ],
        ),
        migrations.AddField(
            model_name='army',
            name='commander',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armies', to='armies.commander'),
        ),
        migrations.CreateModel(
            name='Upgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cost', models.PositiveIntegerField(default=25)),
                ('attack_bonus', models.IntegerField(default=0)),
                ('defense_bonus', models.IntegerField(default=0)),
                ('health_bonus', models.IntegerField(default=0)),
                ('speed_bonus', models.IntegerField(default=0)),
                ('unit_type', models.ForeignKey(blank=True, help_text='Spécifiez pour cibler une unité précise. Vide = bonus global.', null=True, on_delete=django.db.models.deletion.CASCADE, to='armies.unittype')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='army',
            unique_together={('commander', 'name')},
        ),
        migrations.CreateModel(
            name='ArmyUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('position_x', models.PositiveIntegerField(blank=True, null=True)),
                ('position_y', models.PositiveIntegerField(blank=True, null=True)),
                ('army', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='armies.army')),
                ('unit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armies.unittype')),
            ],
            options={
                'unique_together': {('army', 'unit_type')},
            },
        ),
        migrations.CreateModel(
            name='ArmyUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=1)),
                ('army', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrades', to='armies.army')),
                ('upgrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armies.upgrade')),
            ],
            options={
                'unique_together': {('army', 'upgrade')},
            },
        ),
    ]
