# Generated by Django 5.2.8 on 2025-12-01 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttackPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('positions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('army', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attack_presets', to='armies.army')),
            ],
            options={
                'unique_together': {('army', 'name')},
            },
        ),
    ]
