# Generated by Django 5.2.8 on 2025-12-01 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armies', '0002_attackpreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='unittype',
            name='aoe_radius',
            field=models.PositiveIntegerField(default=0, help_text='Rayon AOE en cases (0 = monocible)'),
        ),
        migrations.AddField(
            model_name='unittype',
            name='attack_speed',
            field=models.FloatField(default=1.0, help_text='Attaques par seconde (cap à 4)'),
        ),
        migrations.AddField(
            model_name='unittype',
            name='crit_chance',
            field=models.FloatField(default=0.1, help_text='Chance de critique (0-1)'),
        ),
        migrations.AddField(
            model_name='unittype',
            name='crit_multiplier',
            field=models.FloatField(default=2.0, help_text='Multiplicateur critique'),
        ),
        migrations.AddField(
            model_name='unittype',
            name='damage_max',
            field=models.FloatField(default=1.1, help_text='Variance dégâts max (multiplicateur)'),
        ),
        migrations.AddField(
            model_name='unittype',
            name='damage_min',
            field=models.FloatField(default=0.9, help_text='Variance dégâts min (multiplicateur)'),
        ),
        migrations.AddField(
            model_name='unittype',
            name='dodge_chance',
            field=models.FloatField(default=0.0, help_text="Chance d'esquive (0-0.5)"),
        ),
        migrations.AddField(
            model_name='unittype',
            name='move_speed',
            field=models.FloatField(default=1.0, help_text='Vitesse de déplacement en cases/s'),
        ),
        migrations.AddField(
            model_name='unittype',
            name='range',
            field=models.PositiveIntegerField(default=1, help_text='Portée en cases (1 = mêlée)'),
        ),
        migrations.AlterField(
            model_name='unittype',
            name='speed',
            field=models.PositiveIntegerField(default=1, help_text="Vitesse d'attaque historique (conservée pour compatibilité)"),
        ),
    ]
