# Generated by Django 5.2.8 on 2025-12-01 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armies', '0003_unittype_aoe_radius_unittype_attack_speed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
