# Generated by Django 5.2.8 on 2025-12-02 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armies', '0005_faction_army_faction_unittype_faction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unittype',
            name='attack',
        ),
    ]
