# Generated by Django 5.2.8 on 2025-11-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siege', '0002_alter_siegeprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='siegeprofile',
            name='default_army',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='siegeprofile',
            name='last_refusal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siegeprofile',
            name='refusals_today',
            field=models.IntegerField(default=0),
        ),
    ]
