# Generated by Django 5.2.8 on 2025-11-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siege', '0003_siegeprofile_default_army_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('cost', models.PositiveIntegerField()),
                ('power', models.PositiveIntegerField()),
                ('emoji', models.CharField(help_text='Representation (e.g. 🏹)', max_length=10)),
            ],
        ),
    ]
