# Generated by Django 5.2.8 on 2025-11-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siege', '0005_auto_20251122_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='attacker_layout',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='battle',
            name='defender_layout',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
