# Generated by Django 5.2.8 on 2025-11-21 10:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('start_clue', models.TextField(help_text='Indice pour trouver le premier QR Code', verbose_name='Indice de départ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Ordre')),
                ('name', models.CharField(help_text='Ex: La fontaine', max_length=100, verbose_name="Nom de l'étape")),
                ('clue_text', models.TextField(help_text='Indice révélé quand on scanne cette étape (pour trouver la suivante)', verbose_name='Indice suivant')),
                ('secret_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('hunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='game.hunt')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('hunt', 'order')},
            },
        ),
        migrations.CreateModel(
            name='PlayerProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0, verbose_name='Points totaux')),
                ('completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.hunt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
                ('current_step', models.ForeignKey(blank=True, help_text='Dernière étape validée', null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.step')),
            ],
            options={
                'unique_together': {('user', 'hunt')},
            },
        ),
        migrations.CreateModel(
            name='PlayerStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('points_earned', models.IntegerField(verbose_name='Points gagnés')),
                ('time_taken_seconds', models.IntegerField(help_text="Temps depuis l'étape précédente", verbose_name='Temps pris (s)')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps_history', to='game.playerprogress')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.step')),
            ],
            options={
                'ordering': ['scanned_at'],
                'unique_together': {('progress', 'step')},
            },
        ),
    ]
