# Generated by Django 5.2.8 on 2025-11-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='first_discovered_at',
            field=models.DateTimeField(blank=True, help_text='Date de la première découverte par un joueur', null=True, verbose_name='Découvert le'),
        ),
    ]
